[toolchain]
#channel = "stable"
channel = "nightly-nightly-2025-05-20" # Some depends library or module is must be nightly and such as: idb, common/error
#channel = "1.87.0"
components = ["rustfmt", "clippy", "llvm-tools"]
